name: Build and deploy

on:
  push:
    # branches: [main]
    workflow_dispatch:

env:
  REGISTRY_URL: <put here the value of $REGISTRY_URL>
  PROJECT: java-runtimes
  RESOURCE_GROUP: rg-java-runtimes
  QUARKUS_APP: quarkus-app
  MICRONAUT_APP: micronaut-app
  SPRING_APP: spring-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

        # TODO: other apps
      - name: Build apps
        run: |
          cd quarkus-app && ./mvnw package

        # TODO: other apps
      - name: Build and push Quarkus container to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY_URL }}/${{ env.PROJECT }}/${{ env.QUARKUS_APP }}:${{ github.sha }}
          file: ./quarkus-app/src/main/docker/Dockerfile.jvm
          context: ./quarkus-app/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # TODO: other apps
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            # az containerapp registry set \
            #   --name ${{ env.QUARKUS_APP }} \
            #   --resource-group ${{ RESOURCE_GROUP }} \
            #   --server ${REGISTRY_URL} \
            #   --username  ${{ secrets.REGISTRY_USERNAME }} \
            #   --password ${{ secrets.REGISTRY_PASSWORD }}
            az containerapp update \
              --name ${{ env.QUARKUS_APP }} \
              --resource-group ${{ RESOURCE_GROUP }} \
              --image ${{ env.REGISTRY_URL }}/${{ env.PROJECT }}/${{ env.QUARKUS_APP }}:${{ github.sha }} \
              --target-port 8701
