name: Build workshop docs and deploy to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: Build and Deploy

    permissions:
      contents: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'

    - name: Generate docs
      run: |
        cd docs
        shopt -s globstar
        npx -y cxa-track -t javascript-0000-yolasors **/*.adoc
        VERSION="sha.$(git rev-parse --short HEAD)"
        perl -i -pe "s/1.0.0-SNAPSHOT/$VERSION/g" pom.xml
        mvn generate-resources
        npx -y @moaw/cli@latest convert docs/src/docs/asciidoc/index.adoc -a docs/src/docs/asciidoc/attributes.json -d docs/target/generated-docs/workshop.md

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/target/generated-docs/
